name: Daily Quote Commit

on:
  schedule:
    - cron: '0 */10 * * *' # Runs the script every 10 minutes

jobs:
  daily_quote_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Set the version of Python you want to use
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run script
        run: python daily_quote.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for pushing commits back to the repository
